logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE

# Con esto la clases del dominio se mapean a json con snake case en lugar de camel case
spring.jackson.property-naming-strategy=SNAKE_CASE
spring.data.mongodb.uri=mongodb+srv://tacs:tacs123*@cluster1.0ymras5.mongodb.net/lucas

cors.allowed-origin=${CORS_ORIGIN:http://localhost:5173}
