logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE

# Con esto la clases del dominio se mapean a json con snake case en lugar de camel case
spring.jackson.property-naming-strategy=SNAKE_CASE
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.replica-set-name=${MONGO_REPLICA_SET_NAME:}

cors.allowed-origin=${CORS_ORIGIN:http://localhost:5173}
