name: Load Test

on:
  push:
    branches:
      - main
      - developer
  pull_request:
    branches:
      - main
      - developer

jobs:
  loadtest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Levantar infra de test
        run: docker compose -f docker-compose.test.yml --profile test up -d mongodb-test mongo-init-test backend-test

      - name: Esperar a que el backend esté listo
        run: |
          docker compose -f docker-compose.test.yml --profile test up -d --wait backend-test

      - name: Correr load test
        run: docker compose -f docker-compose.test.yml --profile test run --rm loadtest

      - name: Bajar infra
        if: always()
	   run: docker compose -f docker-compose.test.yml --profile test down